"""Build the single, autonomous Dyson production module."""
from pathlib import Path
import argparse

ROOT = Path(__file__).resolve().parents[1]
FRONTEND = ROOT / 'custom_components/nikas_dyson/frontend'
SOURCES = ('nikas-specialized-shell.js', 'zoom-controller.js', 'nikas-dyson-panel.js')

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    result = '// Generated by scripts/build_frontend.py; edit frontend/src instead.\n' + '\n'.join(
        (FRONTEND / 'src' / name).read_text() for name in SOURCES
    )
    output = FRONTEND / 'nikas-dyson-panel.js'
    if args.check:
        if not output.is_file() or output.read_text() != result:
            raise SystemExit('Production bundle is missing or stale')
    else:
        output.write_text(result)

if __name__ == '__main__':
    main()
